### PR TITLE
reader: ignore empty messages

### PR DESCRIPTION
**Pull request by hhirtz**
The spec [0] says empty messages should be ignored instead of throwing
an error.

[0] https://tools.ietf.org/html/rfc2812#section-2.3.1

### CODE REVIEW

**Comment by hhirtz** [comment]
build error looks unrelated

**Comment by belak** [comment]
Sorry about all the pushes, I just added tests and am making sure they pass before merging this in.

**Comment by belak** [comment]
Thanks for submitting this! I've been working on IRC packages for years and have somehow never run across this specific issue.

**Comment by belak** [comment]
I've also pushed v3.1.4 and v4.0.0-alpha.6 if you want to start using this today.

**Comment by hhirtz** [comment]
wow, thank you so much for merging this in and releasing a version so quickly!

for the record this has been raised from the irc-slack bridge, might be a bug on their side but it's still better to handle this case!

**Comment by belak** [comment]
I'm glad I was able to help! You just happened to catch me at a good time. :) If it ever takes more than a day or so to get a response, you can also ping me in the #ircdocs channel on Freenode.

**Comment by qaisjp** [comment]
> from the irc-slack bridge

Out of curiosity which bridge is that?

**Pull request merged**
